# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CouponApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  # Pods for CouponApp

  # Network 
    pod 'Alamofire'
    pod 'AlamofireImage'
    
  # Progress
   pod 'SVProgressHUD', '~> 2.2.2' 


  target 'CouponAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CouponAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
