# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CouponApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CouponApp

  # Network 
    pod 'Alamofire', '5.5.0'

  # Kingfisher
    pod 'Kingfisher', '~> 7.0'

  # FMDB
    pod 'FMDB', '2.7.5'

  # Progress
   pod 'SVProgressHUD', '~> 2.2.2' 
 
  # TextInput
    pod 'AnimatedTextInput', '0.5.5'
 
  # Rx
    pod 'RxCocoa', '6.5.0'
    pod 'RxSwift', '6.5.0'
    pod 'RxOptional', '5.0.2'

  target 'CouponAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CouponAppUITests' do
    # Pods for testing
  end

end
